-- Seed data for the fashion template. Generated from lib/data/mock/fashion/,
-- so the Supabase catalog matches the bundled mock data exactly.
-- Run supabase/schema.sql first.

insert into categories (id, name, slug, image) values
  ('women', 'Women', 'women', 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=900&q=80'),
  ('men', 'Men', 'men', 'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=900&q=80'),
  ('dresses', 'Dresses', 'dresses', 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=900&q=80'),
  ('outerwear', 'Outerwear', 'outerwear', 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=900&q=80'),
  ('shoes', 'Shoes', 'shoes', 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=900&q=80'),
  ('accessories', 'Accessories', 'accessories', 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=900&q=80');

insert into products (id, name, description, price_minor, currency, images, category_id, featured, created_at) values
  ('relaxed-linen-shirt', 'Relaxed Linen Shirt', 'A breezy button-down cut from washed European linen. Slightly oversized through the body with a curved hem that works tucked or loose.', 7800, 'USD', '["https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=900&q=80","https://images.unsplash.com/photo-1562157873-818bc0726f68?w=900&q=80"]'::jsonb, 'women', true, '2026-06-28T10:00:00.000Z'),
  ('ribbed-cotton-tee', 'Ribbed Cotton Tee', 'A close-fitting ribbed tee in soft organic cotton. The kind of layer you end up owning in three colors.', 3200, 'USD', '["https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=900&q=80","https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=900&q=80"]'::jsonb, 'women', false, '2026-07-05T10:00:00.000Z'),
  ('high-rise-straight-jeans', 'High-Rise Straight Jeans', 'Rigid denim with a high rise and a clean straight leg that breaks just above the ankle. Fades beautifully with wear.', 9800, 'USD', '["https://images.unsplash.com/photo-1542272604-787c3835535d?w=900&q=80","https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=900&q=80"]'::jsonb, 'women', false, '2026-05-14T10:00:00.000Z'),
  ('pleated-satin-skirt', 'Pleated Satin Skirt', 'A fluid midi skirt in knife-pleated satin that moves with every step. Sits at the natural waist with a hidden zip.', 11200, 'USD', '["https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=900&q=80","https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=900&q=80"]'::jsonb, 'women', false, '2026-04-19T10:00:00.000Z'),
  ('garment-dyed-tee', 'Garment-Dyed Tee', 'A heavyweight cotton tee, garment dyed for a lived-in tone that only gets better with washing.', 3600, 'USD', '["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=900&q=80","https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=900&q=80"]'::jsonb, 'men', false, '2026-06-11T10:00:00.000Z'),
  ('oxford-button-down', 'Oxford Button-Down', 'The classic oxford, done properly. Dense basketweave cotton, a soft unlined collar, and mother-of-pearl buttons.', 8800, 'USD', '["https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=900&q=80","https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?w=900&q=80"]'::jsonb, 'men', false, '2026-03-22T10:00:00.000Z'),
  ('merino-crewneck', 'Merino Crewneck Sweater', 'Fine-gauge extrafine merino knitted in a classic crewneck. Light enough for offices, warm enough for evenings.', 12800, 'USD', '["https://images.unsplash.com/photo-1520975954732-35dd22299614?w=900&q=80","https://images.unsplash.com/photo-1610384104075-e05c8cf200c3?w=900&q=80"]'::jsonb, 'men', true, '2026-02-08T10:00:00.000Z'),
  ('pleated-chino-trousers', 'Pleated Chino Trousers', 'Single-pleat chinos with a tapered leg and a touch of stretch. Smart with loafers, easy with sneakers.', 7200, 'USD', '["https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=900&q=80","https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=900&q=80"]'::jsonb, 'men', false, '2026-05-30T10:00:00.000Z'),
  ('wrap-midi-dress', 'Wrap Midi Dress', 'A true wrap dress in crinkled viscose with a flattering V-neck and a skirt that falls to mid-calf.', 12400, 'USD', '["https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=900&q=80","https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=900&q=80"]'::jsonb, 'dresses', true, '2026-06-20T10:00:00.000Z'),
  ('linen-sundress', 'Linen Sundress', 'An easy A-line sundress in midweight linen with adjustable straps and deep side pockets.', 9200, 'USD', '["https://images.unsplash.com/photo-1502716119720-b23a93e5fe1b?w=900&q=80","https://images.unsplash.com/photo-1509631179647-0177331693ae?w=900&q=80"]'::jsonb, 'dresses', false, '2026-07-08T10:00:00.000Z'),
  ('pleated-evening-dress', 'Pleated Evening Dress', 'Fine sunray pleats from shoulder to hem in a floor-skimming silhouette. Quietly dramatic.', 16800, 'USD', '["https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=900&q=80","https://images.unsplash.com/photo-1487222477894-8943e31ef7b2?w=900&q=80"]'::jsonb, 'dresses', false, '2026-01-25T10:00:00.000Z'),
  ('knit-sweater-dress', 'Knit Sweater Dress', 'A ribbed knit dress that skims rather than clings, with a mock neck and side slits for ease.', 10800, 'USD', '["https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=900&q=80","https://images.unsplash.com/photo-1495385794356-15371f348c31?w=900&q=80"]'::jsonb, 'dresses', false, '2026-02-27T10:00:00.000Z'),
  ('belted-trench-coat', 'Belted Trench Coat', 'A double-breasted trench in bonded cotton twill with storm flaps and a waist belt. The forever coat.', 19800, 'USD', '["https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=900&q=80","https://images.unsplash.com/photo-1520975916090-3105956dac38?w=900&q=80"]'::jsonb, 'outerwear', true, '2026-03-08T10:00:00.000Z'),
  ('cropped-denim-jacket', 'Cropped Denim Jacket', 'A boxy, cropped trucker jacket in rigid denim. Cut to sit right at the waistband of high-rise jeans.', 9800, 'USD', '["https://images.unsplash.com/photo-1527016021513-b09758b777bd?w=900&q=80","https://images.unsplash.com/photo-1543076447-215ad9ba6923?w=900&q=80"]'::jsonb, 'outerwear', false, '2026-06-02T10:00:00.000Z'),
  ('leather-biker-jacket', 'Leather Biker Jacket', 'Vegetable-tanned lambskin with an asymmetric zip and just enough hardware. Breaks in like a favorite record.', 24800, 'USD', '["https://images.unsplash.com/photo-1551028719-00167b16eac5?w=900&q=80","https://images.unsplash.com/photo-1520975661595-6453be3f7070?w=900&q=80"]'::jsonb, 'outerwear', false, '2026-04-05T10:00:00.000Z'),
  ('wool-overcoat', 'Wool Overcoat', 'A single-breasted overcoat in brushed Italian wool, cut long with a clean shoulder. Tailoring without the fuss.', 22800, 'USD', '["https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=900&q=80","https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=900&q=80"]'::jsonb, 'outerwear', true, '2026-01-12T10:00:00.000Z'),
  ('minimal-leather-sneakers', 'Minimal Leather Sneakers', 'Clean court sneakers in full-grain leather on a cupsole, with zero visible branding.', 12800, 'USD', '["https://images.unsplash.com/photo-1549298916-b41d501d3772?w=900&q=80","https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=900&q=80"]'::jsonb, 'shoes', true, '2026-05-21T10:00:00.000Z'),
  ('suede-chelsea-boots', 'Suede Chelsea Boots', 'Almond-toe Chelsea boots in water-resistant suede with elastic gussets and a stacked heel.', 16800, 'USD', '["https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=900&q=80","https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=900&q=80"]'::jsonb, 'shoes', false, '2026-02-14T10:00:00.000Z'),
  ('canvas-high-tops', 'Canvas High-Tops', 'High-top sneakers in heavy duck canvas with a vulcanized sole. A blank slate for everything you wear.', 6800, 'USD', '["https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=900&q=80","https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=900&q=80"]'::jsonb, 'shoes', false, '2026-06-25T10:00:00.000Z'),
  ('strappy-heeled-sandals', 'Strappy Heeled Sandals', 'Barely-there sandals with slim leather straps and a sculpted 70mm heel you can actually walk in.', 9800, 'USD', '["https://images.unsplash.com/photo-1596703263926-eb0762ee17e4?w=900&q=80","https://images.unsplash.com/photo-1518049362265-d5b2a6467637?w=900&q=80"]'::jsonb, 'shoes', false, '2026-07-12T10:00:00.000Z'),
  ('structured-leather-tote', 'Structured Leather Tote', 'A clean-lined tote in pebbled leather that holds a 13-inch laptop flat. Unlined, rivet-reinforced, built to age well.', 14800, 'USD', '["https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=900&q=80","https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=900&q=80"]'::jsonb, 'accessories', true, '2026-04-28T10:00:00.000Z'),
  ('minimalist-watch', 'Minimalist Watch', 'A 36mm brushed steel case, domed sapphire glass, and an Italian leather strap. Tells the time, nothing else.', 15800, 'USD', '["https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=900&q=80","https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=900&q=80"]'::jsonb, 'accessories', false, '2026-03-15T10:00:00.000Z'),
  ('acetate-sunglasses', 'Acetate Sunglasses', 'Hand-polished acetate frames with UV400 lenses, somewhere between round and square. Unisex fit.', 7800, 'USD', '["https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=900&q=80","https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=900&q=80"]'::jsonb, 'accessories', false, '2026-05-07T10:00:00.000Z'),
  ('canvas-weekender', 'Canvas Weekender Bag', 'A carry-on-sized duffle in waxed canvas with leather handles and a detachable shoulder strap.', 11800, 'USD', '["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=900&q=80","https://images.unsplash.com/photo-1547949003-9792a18a2601?w=900&q=80"]'::jsonb, 'accessories', false, '2026-01-30T10:00:00.000Z');

insert into variants (id, product_id, name, options, price_override_minor, image) values
  ('relaxed-linen-shirt-xs-white', 'relaxed-linen-shirt', 'XS / White', '{"size":"XS","color":"White"}'::jsonb, null, null),
  ('relaxed-linen-shirt-xs-sand', 'relaxed-linen-shirt', 'XS / Sand', '{"size":"XS","color":"Sand"}'::jsonb, null, null),
  ('relaxed-linen-shirt-s-white', 'relaxed-linen-shirt', 'S / White', '{"size":"S","color":"White"}'::jsonb, null, null),
  ('relaxed-linen-shirt-s-sand', 'relaxed-linen-shirt', 'S / Sand', '{"size":"S","color":"Sand"}'::jsonb, null, null),
  ('relaxed-linen-shirt-m-white', 'relaxed-linen-shirt', 'M / White', '{"size":"M","color":"White"}'::jsonb, null, null),
  ('relaxed-linen-shirt-m-sand', 'relaxed-linen-shirt', 'M / Sand', '{"size":"M","color":"Sand"}'::jsonb, null, null),
  ('relaxed-linen-shirt-l-white', 'relaxed-linen-shirt', 'L / White', '{"size":"L","color":"White"}'::jsonb, null, null),
  ('relaxed-linen-shirt-l-sand', 'relaxed-linen-shirt', 'L / Sand', '{"size":"L","color":"Sand"}'::jsonb, null, null),
  ('ribbed-cotton-tee-xs-black', 'ribbed-cotton-tee', 'XS / Black', '{"size":"XS","color":"Black"}'::jsonb, null, null),
  ('ribbed-cotton-tee-xs-ivory', 'ribbed-cotton-tee', 'XS / Ivory', '{"size":"XS","color":"Ivory"}'::jsonb, null, null),
  ('ribbed-cotton-tee-s-black', 'ribbed-cotton-tee', 'S / Black', '{"size":"S","color":"Black"}'::jsonb, null, null),
  ('ribbed-cotton-tee-s-ivory', 'ribbed-cotton-tee', 'S / Ivory', '{"size":"S","color":"Ivory"}'::jsonb, null, null),
  ('ribbed-cotton-tee-m-black', 'ribbed-cotton-tee', 'M / Black', '{"size":"M","color":"Black"}'::jsonb, null, null),
  ('ribbed-cotton-tee-m-ivory', 'ribbed-cotton-tee', 'M / Ivory', '{"size":"M","color":"Ivory"}'::jsonb, null, null),
  ('ribbed-cotton-tee-l-black', 'ribbed-cotton-tee', 'L / Black', '{"size":"L","color":"Black"}'::jsonb, null, null),
  ('ribbed-cotton-tee-l-ivory', 'ribbed-cotton-tee', 'L / Ivory', '{"size":"L","color":"Ivory"}'::jsonb, null, null),
  ('high-rise-straight-jeans-24-indigo', 'high-rise-straight-jeans', '24 / Indigo', '{"size":"24","color":"Indigo"}'::jsonb, null, null),
  ('high-rise-straight-jeans-24-washed-black', 'high-rise-straight-jeans', '24 / Washed Black', '{"size":"24","color":"Washed Black"}'::jsonb, null, null),
  ('high-rise-straight-jeans-26-indigo', 'high-rise-straight-jeans', '26 / Indigo', '{"size":"26","color":"Indigo"}'::jsonb, null, null),
  ('high-rise-straight-jeans-26-washed-black', 'high-rise-straight-jeans', '26 / Washed Black', '{"size":"26","color":"Washed Black"}'::jsonb, null, null),
  ('high-rise-straight-jeans-28-indigo', 'high-rise-straight-jeans', '28 / Indigo', '{"size":"28","color":"Indigo"}'::jsonb, null, null),
  ('high-rise-straight-jeans-28-washed-black', 'high-rise-straight-jeans', '28 / Washed Black', '{"size":"28","color":"Washed Black"}'::jsonb, null, null),
  ('high-rise-straight-jeans-30-indigo', 'high-rise-straight-jeans', '30 / Indigo', '{"size":"30","color":"Indigo"}'::jsonb, null, null),
  ('high-rise-straight-jeans-30-washed-black', 'high-rise-straight-jeans', '30 / Washed Black', '{"size":"30","color":"Washed Black"}'::jsonb, null, null),
  ('pleated-satin-skirt-xs-champagne', 'pleated-satin-skirt', 'XS / Champagne', '{"size":"XS","color":"Champagne"}'::jsonb, null, null),
  ('pleated-satin-skirt-s-champagne', 'pleated-satin-skirt', 'S / Champagne', '{"size":"S","color":"Champagne"}'::jsonb, null, null),
  ('pleated-satin-skirt-m-champagne', 'pleated-satin-skirt', 'M / Champagne', '{"size":"M","color":"Champagne"}'::jsonb, null, null),
  ('pleated-satin-skirt-l-champagne', 'pleated-satin-skirt', 'L / Champagne', '{"size":"L","color":"Champagne"}'::jsonb, null, null),
  ('garment-dyed-tee-s-faded-navy', 'garment-dyed-tee', 'S / Faded Navy', '{"size":"S","color":"Faded Navy"}'::jsonb, null, null),
  ('garment-dyed-tee-s-clay', 'garment-dyed-tee', 'S / Clay', '{"size":"S","color":"Clay"}'::jsonb, null, null),
  ('garment-dyed-tee-m-faded-navy', 'garment-dyed-tee', 'M / Faded Navy', '{"size":"M","color":"Faded Navy"}'::jsonb, null, null),
  ('garment-dyed-tee-m-clay', 'garment-dyed-tee', 'M / Clay', '{"size":"M","color":"Clay"}'::jsonb, null, null),
  ('garment-dyed-tee-l-faded-navy', 'garment-dyed-tee', 'L / Faded Navy', '{"size":"L","color":"Faded Navy"}'::jsonb, null, null),
  ('garment-dyed-tee-l-clay', 'garment-dyed-tee', 'L / Clay', '{"size":"L","color":"Clay"}'::jsonb, null, null),
  ('garment-dyed-tee-xl-faded-navy', 'garment-dyed-tee', 'XL / Faded Navy', '{"size":"XL","color":"Faded Navy"}'::jsonb, null, null),
  ('garment-dyed-tee-xl-clay', 'garment-dyed-tee', 'XL / Clay', '{"size":"XL","color":"Clay"}'::jsonb, null, null),
  ('oxford-button-down-s-white', 'oxford-button-down', 'S / White', '{"size":"S","color":"White"}'::jsonb, null, null),
  ('oxford-button-down-s-blue-stripe', 'oxford-button-down', 'S / Blue Stripe', '{"size":"S","color":"Blue Stripe"}'::jsonb, null, null),
  ('oxford-button-down-m-white', 'oxford-button-down', 'M / White', '{"size":"M","color":"White"}'::jsonb, null, null),
  ('oxford-button-down-m-blue-stripe', 'oxford-button-down', 'M / Blue Stripe', '{"size":"M","color":"Blue Stripe"}'::jsonb, null, null),
  ('oxford-button-down-l-white', 'oxford-button-down', 'L / White', '{"size":"L","color":"White"}'::jsonb, null, null),
  ('oxford-button-down-l-blue-stripe', 'oxford-button-down', 'L / Blue Stripe', '{"size":"L","color":"Blue Stripe"}'::jsonb, null, null),
  ('oxford-button-down-xl-white', 'oxford-button-down', 'XL / White', '{"size":"XL","color":"White"}'::jsonb, null, null),
  ('oxford-button-down-xl-blue-stripe', 'oxford-button-down', 'XL / Blue Stripe', '{"size":"XL","color":"Blue Stripe"}'::jsonb, null, null),
  ('merino-crewneck-s-charcoal', 'merino-crewneck', 'S / Charcoal', '{"size":"S","color":"Charcoal"}'::jsonb, null, null),
  ('merino-crewneck-s-oatmeal', 'merino-crewneck', 'S / Oatmeal', '{"size":"S","color":"Oatmeal"}'::jsonb, null, null),
  ('merino-crewneck-m-charcoal', 'merino-crewneck', 'M / Charcoal', '{"size":"M","color":"Charcoal"}'::jsonb, null, null),
  ('merino-crewneck-m-oatmeal', 'merino-crewneck', 'M / Oatmeal', '{"size":"M","color":"Oatmeal"}'::jsonb, null, null),
  ('merino-crewneck-l-charcoal', 'merino-crewneck', 'L / Charcoal', '{"size":"L","color":"Charcoal"}'::jsonb, null, null),
  ('merino-crewneck-l-oatmeal', 'merino-crewneck', 'L / Oatmeal', '{"size":"L","color":"Oatmeal"}'::jsonb, null, null),
  ('merino-crewneck-xl-charcoal', 'merino-crewneck', 'XL / Charcoal', '{"size":"XL","color":"Charcoal"}'::jsonb, null, null),
  ('merino-crewneck-xl-oatmeal', 'merino-crewneck', 'XL / Oatmeal', '{"size":"XL","color":"Oatmeal"}'::jsonb, null, null),
  ('pleated-chino-trousers-30-stone', 'pleated-chino-trousers', '30 / Stone', '{"size":"30","color":"Stone"}'::jsonb, null, null),
  ('pleated-chino-trousers-30-olive', 'pleated-chino-trousers', '30 / Olive', '{"size":"30","color":"Olive"}'::jsonb, null, null),
  ('pleated-chino-trousers-32-stone', 'pleated-chino-trousers', '32 / Stone', '{"size":"32","color":"Stone"}'::jsonb, null, null),
  ('pleated-chino-trousers-32-olive', 'pleated-chino-trousers', '32 / Olive', '{"size":"32","color":"Olive"}'::jsonb, null, null),
  ('pleated-chino-trousers-34-stone', 'pleated-chino-trousers', '34 / Stone', '{"size":"34","color":"Stone"}'::jsonb, null, null),
  ('pleated-chino-trousers-34-olive', 'pleated-chino-trousers', '34 / Olive', '{"size":"34","color":"Olive"}'::jsonb, null, null),
  ('pleated-chino-trousers-36-stone', 'pleated-chino-trousers', '36 / Stone', '{"size":"36","color":"Stone"}'::jsonb, null, null),
  ('pleated-chino-trousers-36-olive', 'pleated-chino-trousers', '36 / Olive', '{"size":"36","color":"Olive"}'::jsonb, null, null),
  ('wrap-midi-dress-xs-black', 'wrap-midi-dress', 'XS / Black', '{"size":"XS","color":"Black"}'::jsonb, null, null),
  ('wrap-midi-dress-xs-terracotta', 'wrap-midi-dress', 'XS / Terracotta', '{"size":"XS","color":"Terracotta"}'::jsonb, null, null),
  ('wrap-midi-dress-s-black', 'wrap-midi-dress', 'S / Black', '{"size":"S","color":"Black"}'::jsonb, null, null),
  ('wrap-midi-dress-s-terracotta', 'wrap-midi-dress', 'S / Terracotta', '{"size":"S","color":"Terracotta"}'::jsonb, null, null),
  ('wrap-midi-dress-m-black', 'wrap-midi-dress', 'M / Black', '{"size":"M","color":"Black"}'::jsonb, null, null),
  ('wrap-midi-dress-m-terracotta', 'wrap-midi-dress', 'M / Terracotta', '{"size":"M","color":"Terracotta"}'::jsonb, null, null),
  ('wrap-midi-dress-l-black', 'wrap-midi-dress', 'L / Black', '{"size":"L","color":"Black"}'::jsonb, null, null),
  ('wrap-midi-dress-l-terracotta', 'wrap-midi-dress', 'L / Terracotta', '{"size":"L","color":"Terracotta"}'::jsonb, null, null),
  ('linen-sundress-xs-natural', 'linen-sundress', 'XS / Natural', '{"size":"XS","color":"Natural"}'::jsonb, null, null),
  ('linen-sundress-xs-sage', 'linen-sundress', 'XS / Sage', '{"size":"XS","color":"Sage"}'::jsonb, null, null),
  ('linen-sundress-s-natural', 'linen-sundress', 'S / Natural', '{"size":"S","color":"Natural"}'::jsonb, null, null),
  ('linen-sundress-s-sage', 'linen-sundress', 'S / Sage', '{"size":"S","color":"Sage"}'::jsonb, null, null),
  ('linen-sundress-m-natural', 'linen-sundress', 'M / Natural', '{"size":"M","color":"Natural"}'::jsonb, null, null),
  ('linen-sundress-m-sage', 'linen-sundress', 'M / Sage', '{"size":"M","color":"Sage"}'::jsonb, null, null),
  ('linen-sundress-l-natural', 'linen-sundress', 'L / Natural', '{"size":"L","color":"Natural"}'::jsonb, null, null),
  ('linen-sundress-l-sage', 'linen-sundress', 'L / Sage', '{"size":"L","color":"Sage"}'::jsonb, null, null),
  ('pleated-evening-dress-xs-midnight', 'pleated-evening-dress', 'XS / Midnight', '{"size":"XS","color":"Midnight"}'::jsonb, null, null),
  ('pleated-evening-dress-s-midnight', 'pleated-evening-dress', 'S / Midnight', '{"size":"S","color":"Midnight"}'::jsonb, null, null),
  ('pleated-evening-dress-m-midnight', 'pleated-evening-dress', 'M / Midnight', '{"size":"M","color":"Midnight"}'::jsonb, null, null),
  ('knit-sweater-dress-xs-camel', 'knit-sweater-dress', 'XS / Camel', '{"size":"XS","color":"Camel"}'::jsonb, null, null),
  ('knit-sweater-dress-xs-black', 'knit-sweater-dress', 'XS / Black', '{"size":"XS","color":"Black"}'::jsonb, null, null),
  ('knit-sweater-dress-s-camel', 'knit-sweater-dress', 'S / Camel', '{"size":"S","color":"Camel"}'::jsonb, null, null),
  ('knit-sweater-dress-s-black', 'knit-sweater-dress', 'S / Black', '{"size":"S","color":"Black"}'::jsonb, null, null),
  ('knit-sweater-dress-m-camel', 'knit-sweater-dress', 'M / Camel', '{"size":"M","color":"Camel"}'::jsonb, null, null),
  ('knit-sweater-dress-m-black', 'knit-sweater-dress', 'M / Black', '{"size":"M","color":"Black"}'::jsonb, null, null),
  ('knit-sweater-dress-l-camel', 'knit-sweater-dress', 'L / Camel', '{"size":"L","color":"Camel"}'::jsonb, null, null),
  ('knit-sweater-dress-l-black', 'knit-sweater-dress', 'L / Black', '{"size":"L","color":"Black"}'::jsonb, null, null),
  ('belted-trench-coat-xs-khaki', 'belted-trench-coat', 'XS / Khaki', '{"size":"XS","color":"Khaki"}'::jsonb, null, null),
  ('belted-trench-coat-s-khaki', 'belted-trench-coat', 'S / Khaki', '{"size":"S","color":"Khaki"}'::jsonb, null, null),
  ('belted-trench-coat-m-khaki', 'belted-trench-coat', 'M / Khaki', '{"size":"M","color":"Khaki"}'::jsonb, null, null),
  ('belted-trench-coat-l-khaki', 'belted-trench-coat', 'L / Khaki', '{"size":"L","color":"Khaki"}'::jsonb, null, null),
  ('cropped-denim-jacket-xs-mid-wash', 'cropped-denim-jacket', 'XS / Mid Wash', '{"size":"XS","color":"Mid Wash"}'::jsonb, null, null),
  ('cropped-denim-jacket-s-mid-wash', 'cropped-denim-jacket', 'S / Mid Wash', '{"size":"S","color":"Mid Wash"}'::jsonb, null, null),
  ('cropped-denim-jacket-m-mid-wash', 'cropped-denim-jacket', 'M / Mid Wash', '{"size":"M","color":"Mid Wash"}'::jsonb, null, null),
  ('cropped-denim-jacket-l-mid-wash', 'cropped-denim-jacket', 'L / Mid Wash', '{"size":"L","color":"Mid Wash"}'::jsonb, null, null),
  ('leather-biker-jacket-s-black', 'leather-biker-jacket', 'S / Black', '{"size":"S","color":"Black"}'::jsonb, null, null),
  ('leather-biker-jacket-s-oxblood', 'leather-biker-jacket', 'S / Oxblood', '{"size":"S","color":"Oxblood"}'::jsonb, 26800, null),
  ('leather-biker-jacket-m-black', 'leather-biker-jacket', 'M / Black', '{"size":"M","color":"Black"}'::jsonb, null, null),
  ('leather-biker-jacket-m-oxblood', 'leather-biker-jacket', 'M / Oxblood', '{"size":"M","color":"Oxblood"}'::jsonb, 26800, null),
  ('leather-biker-jacket-l-black', 'leather-biker-jacket', 'L / Black', '{"size":"L","color":"Black"}'::jsonb, null, null),
  ('leather-biker-jacket-l-oxblood', 'leather-biker-jacket', 'L / Oxblood', '{"size":"L","color":"Oxblood"}'::jsonb, 26800, null),
  ('wool-overcoat-s-graphite', 'wool-overcoat', 'S / Graphite', '{"size":"S","color":"Graphite"}'::jsonb, null, null),
  ('wool-overcoat-s-camel', 'wool-overcoat', 'S / Camel', '{"size":"S","color":"Camel"}'::jsonb, null, null),
  ('wool-overcoat-m-graphite', 'wool-overcoat', 'M / Graphite', '{"size":"M","color":"Graphite"}'::jsonb, null, null),
  ('wool-overcoat-m-camel', 'wool-overcoat', 'M / Camel', '{"size":"M","color":"Camel"}'::jsonb, null, null),
  ('wool-overcoat-l-graphite', 'wool-overcoat', 'L / Graphite', '{"size":"L","color":"Graphite"}'::jsonb, null, null),
  ('wool-overcoat-l-camel', 'wool-overcoat', 'L / Camel', '{"size":"L","color":"Camel"}'::jsonb, null, null),
  ('wool-overcoat-xl-graphite', 'wool-overcoat', 'XL / Graphite', '{"size":"XL","color":"Graphite"}'::jsonb, null, null),
  ('wool-overcoat-xl-camel', 'wool-overcoat', 'XL / Camel', '{"size":"XL","color":"Camel"}'::jsonb, null, null),
  ('minimal-leather-sneakers-38-white', 'minimal-leather-sneakers', '38 / White', '{"size":"38","color":"White"}'::jsonb, null, null),
  ('minimal-leather-sneakers-38-off-white', 'minimal-leather-sneakers', '38 / Off-White', '{"size":"38","color":"Off-White"}'::jsonb, null, null),
  ('minimal-leather-sneakers-40-white', 'minimal-leather-sneakers', '40 / White', '{"size":"40","color":"White"}'::jsonb, null, null),
  ('minimal-leather-sneakers-40-off-white', 'minimal-leather-sneakers', '40 / Off-White', '{"size":"40","color":"Off-White"}'::jsonb, null, null),
  ('minimal-leather-sneakers-42-white', 'minimal-leather-sneakers', '42 / White', '{"size":"42","color":"White"}'::jsonb, null, null),
  ('minimal-leather-sneakers-42-off-white', 'minimal-leather-sneakers', '42 / Off-White', '{"size":"42","color":"Off-White"}'::jsonb, null, null),
  ('minimal-leather-sneakers-44-white', 'minimal-leather-sneakers', '44 / White', '{"size":"44","color":"White"}'::jsonb, null, null),
  ('minimal-leather-sneakers-44-off-white', 'minimal-leather-sneakers', '44 / Off-White', '{"size":"44","color":"Off-White"}'::jsonb, null, null),
  ('suede-chelsea-boots-38-taupe', 'suede-chelsea-boots', '38 / Taupe', '{"size":"38","color":"Taupe"}'::jsonb, null, null),
  ('suede-chelsea-boots-38-dark-brown', 'suede-chelsea-boots', '38 / Dark Brown', '{"size":"38","color":"Dark Brown"}'::jsonb, null, null),
  ('suede-chelsea-boots-40-taupe', 'suede-chelsea-boots', '40 / Taupe', '{"size":"40","color":"Taupe"}'::jsonb, null, null),
  ('suede-chelsea-boots-40-dark-brown', 'suede-chelsea-boots', '40 / Dark Brown', '{"size":"40","color":"Dark Brown"}'::jsonb, null, null),
  ('suede-chelsea-boots-42-taupe', 'suede-chelsea-boots', '42 / Taupe', '{"size":"42","color":"Taupe"}'::jsonb, null, null),
  ('suede-chelsea-boots-42-dark-brown', 'suede-chelsea-boots', '42 / Dark Brown', '{"size":"42","color":"Dark Brown"}'::jsonb, null, null),
  ('suede-chelsea-boots-44-taupe', 'suede-chelsea-boots', '44 / Taupe', '{"size":"44","color":"Taupe"}'::jsonb, null, null),
  ('suede-chelsea-boots-44-dark-brown', 'suede-chelsea-boots', '44 / Dark Brown', '{"size":"44","color":"Dark Brown"}'::jsonb, null, null),
  ('canvas-high-tops-37-ecru', 'canvas-high-tops', '37 / Ecru', '{"size":"37","color":"Ecru"}'::jsonb, null, null),
  ('canvas-high-tops-37-black', 'canvas-high-tops', '37 / Black', '{"size":"37","color":"Black"}'::jsonb, null, null),
  ('canvas-high-tops-39-ecru', 'canvas-high-tops', '39 / Ecru', '{"size":"39","color":"Ecru"}'::jsonb, null, null),
  ('canvas-high-tops-39-black', 'canvas-high-tops', '39 / Black', '{"size":"39","color":"Black"}'::jsonb, null, null),
  ('canvas-high-tops-41-ecru', 'canvas-high-tops', '41 / Ecru', '{"size":"41","color":"Ecru"}'::jsonb, null, null),
  ('canvas-high-tops-41-black', 'canvas-high-tops', '41 / Black', '{"size":"41","color":"Black"}'::jsonb, null, null),
  ('canvas-high-tops-43-ecru', 'canvas-high-tops', '43 / Ecru', '{"size":"43","color":"Ecru"}'::jsonb, null, null),
  ('canvas-high-tops-43-black', 'canvas-high-tops', '43 / Black', '{"size":"43","color":"Black"}'::jsonb, null, null),
  ('strappy-heeled-sandals-36-tan', 'strappy-heeled-sandals', '36 / Tan', '{"size":"36","color":"Tan"}'::jsonb, null, null),
  ('strappy-heeled-sandals-37-tan', 'strappy-heeled-sandals', '37 / Tan', '{"size":"37","color":"Tan"}'::jsonb, null, null),
  ('strappy-heeled-sandals-38-tan', 'strappy-heeled-sandals', '38 / Tan', '{"size":"38","color":"Tan"}'::jsonb, null, null),
  ('strappy-heeled-sandals-39-tan', 'strappy-heeled-sandals', '39 / Tan', '{"size":"39","color":"Tan"}'::jsonb, null, null),
  ('structured-leather-tote-tan', 'structured-leather-tote', 'Tan', '{"size":"One Size","color":"Tan"}'::jsonb, null, null),
  ('structured-leather-tote-black', 'structured-leather-tote', 'Black', '{"size":"One Size","color":"Black"}'::jsonb, null, null),
  ('minimalist-watch-black-strap', 'minimalist-watch', 'Black Strap', '{"size":"One Size","color":"Black Strap"}'::jsonb, null, null),
  ('minimalist-watch-tan-strap', 'minimalist-watch', 'Tan Strap', '{"size":"One Size","color":"Tan Strap"}'::jsonb, null, null),
  ('acetate-sunglasses-tortoise', 'acetate-sunglasses', 'Tortoise', '{"size":"One Size","color":"Tortoise"}'::jsonb, null, null),
  ('acetate-sunglasses-matte-black', 'acetate-sunglasses', 'Matte Black', '{"size":"One Size","color":"Matte Black"}'::jsonb, null, null),
  ('canvas-weekender-field-green', 'canvas-weekender', 'Field Green', '{"size":"One Size","color":"Field Green"}'::jsonb, null, null);
